name: Release (tw)

on:
  push:
    tags:
    - 'v*'

jobs:
  job1:
    name: Create Release
    runs-on: ubuntu-latest
    outputs: 
      upload_url: ${{ steps.create_release.outputs.upload_url }} 
    
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false

  job2:
    name: Build
    needs: job1
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macOS-latest
    steps:
      - uses: actions/checkout@v2

      - name: make all
        run: |
          cd t1
          mkdir build
          make
      
      - name: Create tarball
        uses: master-atul/tar-action@v1.0.2
        id: compress
        with:
          command: c
          cwd: ./t1
          files: |
            ./build/hw1
          outPath: hw1-${{ matrix.os }}.tar.gz
      
      - name: Upload assets
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.job1.outputs.upload_url }}
          asset_path: t1/build/${{ matrix.os }}.tar.gz
          asset_name: ${{ matrix.os }}.tar.gz
          asset_content_type: application/gzip
